# Site Settings
title: "郭毅芙 - Yifu Guo"
name: "Yifu Guo (郭毅芙)"
description: "Personal Website"
url: https://euyis1019.github.io
baseurl: ""

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - Dockerfile
  - .git
  - .gitignore
